microsoft/DirectX-Specs

- d3d/RenderPasses.md
Spec got stale from implementation.
> Remove SetDescriptorHeaps from disallowed list of APIs.

- d3d/HLSL_ShaderModel6_5.md
> Fix DXR link

- d3d/MeshShader.md
> Fix formatting

- d3d/D3D12onWin7.md
Please review. We should hold off the actual merging until we have a new nupkg created and ready to share.
> Updated with SHA-2 requirement (first draft)

- d3d/DeviceRemovedExtendedData.md
> Fix tables on DeviceRemovedExtendedData.md

- d3d/Raytracing.md
See https://github.com/microsoft/DirectXShaderCompiler/blob/6775e94ef17d26449413d2074f837fb739e0f16c/include/dxc/Support/HLSLOptions.td#L280
> Correct "-enable-payload-qualifier" command line flag

- d3d/Raytracing.md
"eadsthreads -> threads" typo fix
> "eadsthreads -> threads" typo fix

- d3d/Raytracing.md
> Fix a few small typos

- README.md
- d3d/D3D12EnhancedBarriers.md
Specifications for enhanced barriers.
> D3D12EnhancedBarriers: Publish spec

- d3d/D3D12EnhancedBarriers.md
> Two minor fixes in D3D12EnhancedBarriers.md

- d3d/D3D12EnhancedBarriers.md
Update sample code.
Document AssertTextureLayout and AssertResourceAccess debug interface methods.
Other minor spec cleanup.
> D3D12EnhancedBarriers: Spec cleanup and Assert methods

- d3d/Raytracing.md
> Fix a typo in Raytracing.md

- d3d/HLSL_SM_6_7_Advanced_Texture_Ops.md
- d3d/HLSL_SM_6_7_QuadAny_QuadAll.md
- d3d/HLSL_SM_6_7_Wave_Ops_Include_Helper_Lanes.md
- d3d/HLSL_ShaderModel6_7.md
Overall description and detailed specs for Advanced Texture Ops,
QuadAny/QuadAll, and Wave Ops with Helper Lanes
> Upload Shader Model 6.7 Specs

- d3d/HLSL_SM_6_7_Advanced_Texture_Ops.md
Misformed the anchors for the enhanced barriers spec
> Final link correction for SM 6.7

- d3d/D3D12EnhancedBarriers.md
> D3D12: EnhancedBarriers: Update to the latest spec

- README.md
- d3d/D3D12GPUUploadHeaps.md
Upload GPU upload heaps spec and add it to readme.md
> Upload GPU upload heaps spec

- d3d/D3D12Redistributable.md
> Fix capitialization in paths for images in D3D12Redistributable.md

- d3d/D3D12EnhancedBarriers.md
Clarifying some details on interop with legacy resource barriers based on customer feedback.
> D3D12: Enhanced Barriers: Clarify interop details

- d3d/D3D12EnhancedBarriers.md
Enhanced Barriers: Document initial state for swap chain textures
Enhanced Barriers: Remove stale Sync and Access Validation section
> Enhanced Barriers: Updates based on customer feedback

- d3d/D3D12Redistributable.md
> Fix typo of DIXL to DXIL inside D3D12Redistributable.md

- d3d/HLSL_ShaderModel6_5.md
> fix names of 6.5 intrinsics

- README.md
- d3d/D3D12R9G9B9E5Format.md
Fixed table formatting and added 999E5 to table of content
> Updated Table of Content with 999E5

- DirectSR/DirectSR.md
Adding DirectSR spec, which is now available for public preview in Agility SDK 1.714-preview
> DirectSR: Add DirectSR spec

- README.md
- d3d/Application_Specific_Driver_State_v0_07.md
- d3d/D3D12TightPlacedResourceAlignment.md
- d3d/D3D12_Video_Encoding_HEVC_422_444.md
- d3d/D3D12_Video_Encoding_ReadableReconpic.md
- d3d/D3D12_Video_Encoding_Stats_Metadata.md
- d3d/D3D12_Video_Encoding_SubregionNotification.md
- d3d/D3D12_Video_Encoding_Texture_QPMap_DirtyMap_MotionVectors.md
- d3d/RecreateAtGpuva-public.md
Migrated specs for the Aglity SDK release
> Agility SDK 1.716 and 1.615 Specs

- d3d/WorkGraphs.md
It seems that sometimes, *but not always*, having a loose `|` in text renders it as a table such as at https://microsoft.github.io/DirectX-Specs/d3d/WorkGraphs.html#barrier:
This is also breaking links. By wrapping these function names -which were supposed to be monospace to begin with- in backticks the problem is avoided.
Additionally, `\|` escapes are not always necessary in monospace blocks and sometimes have the adverse behaviour of accidentally rendering:
Unfortunately, even though they're also rendered verbatim in the changelog table at the end, removing them breaks the table. But there are more issues here, because `<li>` is also rendered as-is rather than forming a table:
> WorkGraphs: Wrap pipe symbol (`|`) in monospace to prevent table rendering
