microsoft/DirectX-Specs

- d3d/archive/D3D11_3_FunctionalSpec.htm
The DX11.3 spec describes this.zw swapped compared to what fxc has been doing since 11.0.
> Fix components of the this register

- d3d/BackgroundProcessing.md
Previously, the PIX scenario shows D3D12_MEASUREMENTS_ACTION_DISCARD_PREVIOUS always being called before playing back the frame, when this should only be done the first round around the training loop.
> Update SetBackgroundProcessMode PIX scenario

- d3d/DeviceRemovedExtendedData.md
Apparently the github.io version of the specs doesn't like tables with empty headings.
> Formatting fixes + update context info to 1.2

- d3d/SamplerFeedback.md
- d3d/VariableRateShading.md
Summary of changes
- For sampler feedback
- Revise sampler feedback tier 0.9 to add new limitations involving the SRV passed into feedback-writing methods. These restrictions basically mean the SRV needs to span the full resource and not impose clamping.
- Refine wording around transcode-to-buffer. This change makes it clearer that transcode involving buffers is for non-arrayed feedback maps.
- Clarify that transitivity can only hold for MipRegionUsed feedback maps, not MinMip feedback maps. This scopes down the section on transitivity and adds a note explaining some context. 
- pSrcRect must be null for both encode and decode of MinMip type feedback maps
- Make it clearer that MinMip feedback maps are created against the paired mip level count, but are flattened when you transcode
- …
> Update VRS spec interpolation description; rev SF spec Tier 0.9, other cleanups

- d3d/VariableRateShading.md
This spec update clarifies that 
* import or export of depth or stencil in the pixel shader causes coarse shading, and
* use of coarse shading, conservative rasterization, and centroid interpolation together produces a result equivalent to non-centroid (i.e., center)
> Update VRS spec: PS import or export of depth or stencil causes coarse shading and less common feature intersection

- d3d/VariableRateShading.md
This adds some details around the relationship between VRS tiles and sizing+position of coarse pixels.
> Add sections to VRS spec "Positioning of the Coarse Pixel Grid" and "VRS Tiles"

- d3d/PlanarDepthStencilDDISpec.md
This spec describes the changes to depth/stencil texture formats in D3D12 compared to past versions of D3D.  It was in an internal archive from when D3D12 was first designed, so  this change ports it to markdown posts it for public viewing.
> Add Planar Depth Stencil spec.

- d3d/DepthBoundsTest.md
DepthBoundsTest API: "We will add a CheckFeatureSupport query, e.g. D3D12_FEATURE_D3D12_OPTIONS1, to determine whether this feature is supported based on UMD version." -> "D3D12_FEATURE_D3D12_OPTIONS2"
> DepthBoundsTest refers to OPTIONS2

- d3d/D3D12_FeatureLevel12_2.md
A table of additional flags was not created in the built html at Feature Level 12_2.
> Fix table creation

- d3d/MeshShader.md
Primitive attributes are indexed by primitive, not by vertex so this doesn't make much sense. A likely copy+paste issue from the vertex attributes section which has the same sentence.
> Fix typo for primitive attributes

- d3d/VariableRateShading.md
The spec should properly describe SV_Position.z as an interpolated value that doesn't affect coarse shading.
> Some clarifications in "depth and stencil" section of VRS spec

- README.md
- d3d/ShaderCache.md
These APIs are available in insider SDKs after the 19041 SDK release.
> Add shader cache control API/DDI spec

- README.md
I debated whether I should tag them as coming from external (I had † annotations on them at first) but removed them ecause I assumed that GitHub would tag them as external for me. It doesn't... but maybe this is still fine?
> Add external links to the DXC wiki for shader models/features spec'd there

- d3d/HLSL_SM_6_6_Derivatives.md
Previously, we considered allowing odd dimensions and some leftover language there implied that. 
Removing it to avoid confusion.
> Remove out of date language in SM6.6 derivatives

- d3d/HLSL_ShaderModel6_5.md
Fix the example, it should use WavePrefixSum instead of WaveActiveSum.
Clarifying on the bitmasks part. In fact, the "same" means the (bitmask & active_lanes_bitmask) not the original bitmask.
> Update HLSL_ShaderModel6_5.md to fix error in example and clarify on WaveMultiPrefix*()

- d3d/IndirectDrawing.md
Have been looking closely at this part of the spec and noticed a few extra or missing characters.
> Small typo fixes

- d3d/D3D12VideoEncoding.md
Fix H264 Sequence Parameter Set expected values
frame_mbs_only_flag must be 1
direct_8x8_inference_flag must be 1
> Fix H264 Sequence Parameter Set expected values

- d3d/DeviceRemovedExtendedData.md
Spec was out-of-date. The design of the upcoming ID3D12DeviceRemovedExtendedDataSettings2 has changed.
> DRED: Update ID3D12DeviceRemovedExtendedDataSettings2 design

- d3d/Raytracing.md
CandidateWorldToObject4x3 returns a float4x3, instead of a float 3x4.
> Fixing CandidateWorldToObject4x3 return value

- d3d/VariableRateShading.md
This change 
- adds detail around when validation of SHADING_RATE_SOURCE state take place. It's at Draw-time, not earlier
- clarifies that the SupportsPerVertexShadingRateWithMultipleViewports cap doesn't indicate a per-viewport shading rate.
> Add clarification around shading rate resource state, SupportsPerVertexShadingRateWithMultipleViewports

- d3d/Raytracing.md
D3D12_SERIALIZED_ACCELERATION_STRUCTURE_HEADER -> D3D12_SERIALIZED_RAYTRACING_ACCELERATION_STRUCTURE_HEADER
> Fixed mismatching name

- d3d/Raytracing.md
D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_SHADERS_ASSOCIATION does not exists. It seems to be D3D12_STATE_SUBOBJECT_TYPE_SUBOBJECT_TO_EXPORTS_ASSOCIATION.
> Fix unidentified flag in Raytracing.md

- d3d/HLSL_SM_6_7_Advanced_Texture_Ops.md
The `pos` parameters must be of type `uint3` to include the array index.
> Fix RWTexture2DMSArray operator signatures

- d3d/VariableRateShading.md
Hello,
There was a typo in the sentence: "The shading rates 1x1, 1x2, 2x2 and 2x2 can be requested on all tiers."
It should be  "The shading rates 1x1, 1x2, 2x1 and 2x2 can be requested on all tiers."
Kind regards,
Enrique de Lucas
> Fixed typo in VariableRateShading.md

- d3d/HLSL_ShaderModel6_5.md
Explicitly call out that even though the mask bits for lane 0 and lane 3 seem to create an intersecting subset of lanes, the fact that lane 1 is inactive means that it's bit is ignored in the mask (even when determining if there are intersections) so the masks for lanes 0 and 3 are actually the same.
> Clarify WaveMultiPrefixSum() Illustration

- d3d/BackgroundProcessing.md
SetBackgroundProcessingMode() usage scenario needed to wait on compile results before running RunTheRealBenchmark()
> background processing usage scenario code fix

- d3d/SamplerFeedback.md
Hello there,
I believe I found a redundant _and_ in the Sampler Feedback document so I created this PR to address that minor issue.
Regards,
> Fix typo in SamplerFeedback.md

- d3d/D3D12EnhancedBarriers.md
Hello.
I think this type of barrier must be used with texture resources, not buffer ones.
> Fix description of D3D12_TEXTURE_BARRIER::pResource

- d3d/archive/D3D11_3_FunctionalSpec.htm
Previously the blending precision spec does not take into account 999E5 for clamping of input. As 999E5 is another form of float, it should.
> Revised the blending precision spec for 999E5

- d3d/D3D12EnhancedBarriers.md
Addresses #163 
Adds `D3D12_BARRIER_ACCESS_SHADING_RATE_SOURCE` to list of access bits compatible with `D3D12_BARRIER_SYNC_PIXEL_SHADING`.
Clarifies `D3D12_BARRIER_ACCESS_COMMON` compatibility with various `D3D12_BARRIER_SYNC` bits.
Fills some unintended gaps in other `D3D12_BARRIER_SYNC` bit descriptions.
> D3D12: Enhanced Barriers: Clarify sync and access bit compatibilities

- d3d/WorkGraphs.md
Clarify that barrier translation between old/new DXIL ops depending on shader model is not implemented.
Part of https://github.com/microsoft/DirectXShaderCompiler/issues/6538.
> Clarify unimplemented barrier translation in Work Graphs spec

- d3d/HLSL_SM_6_6_DynamicResources.md
Passing a value from a resource array to an intrinsic doesn't work in DXC. That will be addressed at some point, but in the meantime, we don't want the leading people to use nonfunctional code.
This updates the spec text to avoid the broken usage and makes the example more illustrative of how the resource heaps work.
See https://github.com/microsoft/DirectXShaderCompiler/issues/4520
> Remove nonworking code from Dynamic Resources spec

- d3d/HLSL_SM_6_7_Advanced_Texture_Ops.md
UAVs cannot be created with depth/stencil information. The flags are incompatible.
See: https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_resource_flags
This makes it clear in the spec that the Advanced Texture Operations feature makes no change to that.
> Clarify use of RW MSAA Textures with depth/stencil

- d3d/HLSL_SM_6_6_Derivatives.md
The issue resolution was a relic of a previous version of the spec. It did not reflect the current spec text, which may have misled some readers. The resolution now reflects the current spec language.
> Correct misleading derivatives in compute issue

- d3d/IndependentDevices.md
This was short-handed to `GetConfigInterface()` even though the full function name is `GetConfigurationInterface`. Very unlikely for someone to copy this and run into a symbol error, but it's more clear to mention the full name everywhere.
> IndependentDevices: Fix "reference" to `GetConfigurationInterface()`

- d3d/ShaderCacheRegistrationAPI.md
- d3d/ShaderCompilerPlugin.md
Forward slashes in links for image paths and remove cross-references to un-published spec, inlining missing structs.
> Advanced shader delivery spec link fixes
